### PR TITLE
VisionMamba implementation

### PR DESCRIPTION
**Pull request by AliYoussef97**
Vision Mamba implementation. Forward function contains both forward and backward direction SSM, however, I did not implement the step function as both directions would return a cache while the final output is the combination of both the forward and backward direction.

### CODE REVIEW

**Comment by alxndrTL** [comment]
Thank you for the PR! Have you tried it ?

**Comment by alxndrTL** [comment]
Thanks! I'll merge this now and add comments in the file as well as in the README

**Comment by AliYoussef97** [comment]
> Thanks! I'll merge this now and add comments in the file as well as in the README

Great! I’ll try and add a training script and the full trainable model sometime this month, similar to [this](https://github.com/hustvl/Vim/blob/main/vim/models_mamba.py) (adding cls token, pos embedding, random sequence flips, etc. This PR is the Vision Mamba Block only).

The Vision Mamba block is the “v2” [here](https://github.com/hustvl/Vim/blob/main/mamba-1p1p1/mamba_ssm/modules/mamba_simple.py)(it gets called fron the Block function in the first link), which what this PR is based off.

**Comment by alxndrTL** [comment]
Hello, i'm refactoring your code in `vim.py`, if I understood you correctly, I get get rid of all the things related to the cache right ?

**Comment by AliYoussef97** [comment]
That is correct, I did not implement the step function, only the forward function.

**Pull request merged**
